### ISSUE TITLE
PSDK commands timesout after multiple calls M30

### ISSUE THREAD

**Issue by stevedanomodolor** [dji-sdk/Payload-SDK#151]
For bit of context, currently we use flying the m30 with the psdk software. After running multiple missions with streaming, we notice that all of a sudden, randomly the service call to the psdk times out. I also noticed this behavior when I set the camera source to the m30T based on the enum in the payload sdk.  It seems that the enum is incorrect and that the zoom for the m30/m30T is 2 like the h20 while the wide is 1. Please confirm if this is indeed the case. 

```
typedef enum {
    DJI_LIVEVIEW_CAMERA_SOURCE_DEFAULT = 0,
    DJI_LIVEVIEW_CAMERA_SOURCE_H20_WIDE = 1,
    DJI_LIVEVIEW_CAMERA_SOURCE_H20_ZOOM = 2,
    DJI_LIVEVIEW_CAMERA_SOURCE_H20T_WIDE = 1,
    DJI_LIVEVIEW_CAMERA_SOURCE_H20T_ZOOM = 2,
    DJI_LIVEVIEW_CAMERA_SOURCE_H20T_IR = 3,
    DJI_LIVEVIEW_CAMERA_SOURCE_H20N_WIDE = 1,
    DJI_LIVEVIEW_CAMERA_SOURCE_H20N_ZOOM = 2,
    DJI_LIVEVIEW_CAMERA_SOURCE_H20N_IR = 3,
    DJI_LIVEVIEW_CAMERA_SOURCE_M30_ZOOM = 1,
    DJI_LIVEVIEW_CAMERA_SOURCE_M30_WIDE = 2,
    DJI_LIVEVIEW_CAMERA_SOURCE_M30T_ZOOM = 1,
    DJI_LIVEVIEW_CAMERA_SOURCE_M30T_WIDE = 2,
    DJI_LIVEVIEW_CAMERA_SOURCE_M30T_IR = 3,
    DJI_LIVEVIEW_CAMERA_SOURCE_M3E_VIS = 1,
    DJI_LIVEVIEW_CAMERA_SOURCE_M3T_VIS = 1,
    DJI_LIVEVIEW_CAMERA_SOURCE_M3T_IR = 2,
} E_DjiLiveViewCameraSource;
```

I am not sure it is a problem related to the baudrate or the frequency we set for each of the subscriber. Currently for the M30, we use the following information. Also, it seem the documentation on your payload page  on the frequency and topics available for each drone is incorrect ->https://developer.dji.com/doc/payload-sdk-tutorial/en/function-set/basic-function/info-management.html
```

      baudrate: "921600"
      data_frequency:
        imu: 50
        attitude: 50
        acceleration: 50
        velocity: 50
        angular_velocity: 50
        position: 50
        altitude: 50
        gps_fused_position: 10
        gps_data: 10
        rtk_data: 5
        magnetometer: 50
        rc_channels_data: 1
        gimbal_data: 50
        flight_status: 1
        battery_level: 1
        control_information: 1


````
